# syntax=docker/dockerfile:1
ARG BASE=msvc-wine
FROM $BASE

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && apt-get --no-install-recommends install -y \
    clang \
    clang-tools \
    lld

COPY --link test/hello.c ./

RUN \
    clang_cl="$(find /usr/bin -regextype posix-extended -regex '.*/clang-cl(-[0-9]+)?$' -printf '%f\n' | sort -V | tail -n1)"; \
    for arch in x86 x64 arm arm64; do \
        [ ! -d /opt/msvc/kits/10/lib/*/um/$arch ] || \
        (BIN=/opt/msvc/bin/$arch . /opt/msvc/msvcenv-native.sh && \
            "$clang_cl" --target=$TARGET_TRIPLE hello.c -fuse-ld=lld -Fehello-$arch.exe && \
            clang --target=$TARGET_TRIPLE hello.c -fuse-ld=lld -o hello-$arch.exe \
        ) || exit 1; \
    done
