#!/bin/bash
#
# Copyright (c) 2018 Martin Storsjo
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

. $(dirname $0)/msvcenv.sh

# /showIncludes
unixify_path='/^Note: including file: /{ s/z:([\\/])/\1/i; s,\\,/,g; }'
# /E
unixify_line='/^[[:blank:]]*#[[:blank:]]*line[[:blank:]]/{ s/z:([\\/])/\1/i; s,\\\\,/,g; }'
# Warnings and Errors
unixify_note='/^[zZ]:.*\([[:digit:]]+\): (note|error C[[:digit:]]{4}|warning C[[:digit:]]{4}): /{ s/z:([\\/])/\1/ig; s,\\,/,g; }'

export WINE_MSVC_STDOUT_SED="$unixify_path;$unixify_line;$unixify_note"
export WINE_MSVC_STDERR_SED="$unixify_path"

$(dirname $0)/wine-msvc.sh $BINDIR/cl.exe "$@"

ec=$?
[ $ec -ne 0 ] && exit $ec

# Postprocess
for a in "$@"; do
    case $a in
        [-/]P) arg_P=$a ;;
        [-/]Fi*) arg_Fi=${a:3} ;;
    esac
done

# Unixify paths for /P
if [ -n "$arg_P" ] && [ -f "$arg_Fi" ]; then
    if sed --help 2>&1 | grep '\-i extension' >/dev/null; then
        inplace=(-i '') # BSD sed
    else
        inplace=(-i)    # GNU sed
    fi
    sed "${inplace[@]}" -E 's/\r//;'"$unixify_line" "$arg_Fi"
fi

exit $ec
